### ISSUE TITLE
proxy_ssl_verify_depth to low

### ISSUE THREAD

**Issue by DavidGhiro** [mirainc/funes#32]
I get error message "upstream SSL certificate verify error: (20:unable to get local issuer certificate) while SSL handshaking to upstream" on
- https://arch.nixlab.pl/
- https://ftp.halifax.rwth-aachen.de/archlinux
- https://ftp.spline.inf.fu-berlin.de/mirrors/archlinux/

Setting proxy_ssl_verify_depth 3; instead of proxy_ssl_verify_depth 2; fix it.

**Comment by concreted** [comment]
Thanks for reporting, it seems safe to hardcode this to 3 so this is fixed in https://github.com/mirainc/funes/commit/7cdd81f005051b126064c7f362bc06d9d08bc645 and https://github.com/mirainc/funes/commit/cb2aaceb464963776ea233336356909f1f7220f1. 

This should probably be configurable with a flag or env var, will go back and add that when I have time.
